package model;
// Generated 24/05/2019 03:33:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaProducto generated by hbm2java
 */
public class AuditoriaProducto  implements java.io.Serializable {


     private int id;
     private String nombreant;
     private String descripcionant;
     private Double precioant;
     private Integer stockant;
     private String imageant;
     private Integer descuentoant;
     private Integer idCategoriaant;
     private String nombrenew;
     private String descripcionnew;
     private Double precionew;
     private Integer stocknew;
     private String imagenew;
     private Integer descuentonew;
     private Integer idCategorianew;
     private String usuario;
     private Date modificado;
     private Integer idProducto;

    public AuditoriaProducto() {
    }

	
    public AuditoriaProducto(int id) {
        this.id = id;
    }
    public AuditoriaProducto(int id, String nombreant, String descripcionant, Double precioant, Integer stockant, String imageant, Integer descuentoant, Integer idCategoriaant, String nombrenew, String descripcionnew, Double precionew, Integer stocknew, String imagenew, Integer descuentonew, Integer idCategorianew, String usuario, Date modificado, Integer idProducto) {
       this.id = id;
       this.nombreant = nombreant;
       this.descripcionant = descripcionant;
       this.precioant = precioant;
       this.stockant = stockant;
       this.imageant = imageant;
       this.descuentoant = descuentoant;
       this.idCategoriaant = idCategoriaant;
       this.nombrenew = nombrenew;
       this.descripcionnew = descripcionnew;
       this.precionew = precionew;
       this.stocknew = stocknew;
       this.imagenew = imagenew;
       this.descuentonew = descuentonew;
       this.idCategorianew = idCategorianew;
       this.usuario = usuario;
       this.modificado = modificado;
       this.idProducto = idProducto;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreant() {
        return this.nombreant;
    }
    
    public void setNombreant(String nombreant) {
        this.nombreant = nombreant;
    }
    public String getDescripcionant() {
        return this.descripcionant;
    }
    
    public void setDescripcionant(String descripcionant) {
        this.descripcionant = descripcionant;
    }
    public Double getPrecioant() {
        return this.precioant;
    }
    
    public void setPrecioant(Double precioant) {
        this.precioant = precioant;
    }
    public Integer getStockant() {
        return this.stockant;
    }
    
    public void setStockant(Integer stockant) {
        this.stockant = stockant;
    }
    public String getImageant() {
        return this.imageant;
    }
    
    public void setImageant(String imageant) {
        this.imageant = imageant;
    }
    public Integer getDescuentoant() {
        return this.descuentoant;
    }
    
    public void setDescuentoant(Integer descuentoant) {
        this.descuentoant = descuentoant;
    }
    public Integer getIdCategoriaant() {
        return this.idCategoriaant;
    }
    
    public void setIdCategoriaant(Integer idCategoriaant) {
        this.idCategoriaant = idCategoriaant;
    }
    public String getNombrenew() {
        return this.nombrenew;
    }
    
    public void setNombrenew(String nombrenew) {
        this.nombrenew = nombrenew;
    }
    public String getDescripcionnew() {
        return this.descripcionnew;
    }
    
    public void setDescripcionnew(String descripcionnew) {
        this.descripcionnew = descripcionnew;
    }
    public Double getPrecionew() {
        return this.precionew;
    }
    
    public void setPrecionew(Double precionew) {
        this.precionew = precionew;
    }
    public Integer getStocknew() {
        return this.stocknew;
    }
    
    public void setStocknew(Integer stocknew) {
        this.stocknew = stocknew;
    }
    public String getImagenew() {
        return this.imagenew;
    }
    
    public void setImagenew(String imagenew) {
        this.imagenew = imagenew;
    }
    public Integer getDescuentonew() {
        return this.descuentonew;
    }
    
    public void setDescuentonew(Integer descuentonew) {
        this.descuentonew = descuentonew;
    }
    public Integer getIdCategorianew() {
        return this.idCategorianew;
    }
    
    public void setIdCategorianew(Integer idCategorianew) {
        this.idCategorianew = idCategorianew;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Date modificado) {
        this.modificado = modificado;
    }
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }




}


