package model;
// Generated 24/05/2019 03:33:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaClientes generated by hbm2java
 */
public class AuditoriaClientes  implements java.io.Serializable {


     private int id;
     private String nomant;
     private String apatant;
     private String amatant;
     private String direccionant;
     private Date fenacant;
     private Long telefonoant;
     private String emailant;
     private String usuarioant;
     private String passant;
     private String nomnew;
     private String apatnew;
     private String amatnew;
     private String direccionnew;
     private Date fenacnew;
     private Long telefononew;
     private String emailnew;
     private String usuarionew;
     private String passnew;
     private String usuario;
     private Date modificado;
     private Integer idCliente;

    public AuditoriaClientes() {
    }

	
    public AuditoriaClientes(int id) {
        this.id = id;
    }
    public AuditoriaClientes(int id, String nomant, String apatant, String amatant, String direccionant, Date fenacant, Long telefonoant, String emailant, String usuarioant, String passant, String nomnew, String apatnew, String amatnew, String direccionnew, Date fenacnew, Long telefononew, String emailnew, String usuarionew, String passnew, String usuario, Date modificado, Integer idCliente) {
       this.id = id;
       this.nomant = nomant;
       this.apatant = apatant;
       this.amatant = amatant;
       this.direccionant = direccionant;
       this.fenacant = fenacant;
       this.telefonoant = telefonoant;
       this.emailant = emailant;
       this.usuarioant = usuarioant;
       this.passant = passant;
       this.nomnew = nomnew;
       this.apatnew = apatnew;
       this.amatnew = amatnew;
       this.direccionnew = direccionnew;
       this.fenacnew = fenacnew;
       this.telefononew = telefononew;
       this.emailnew = emailnew;
       this.usuarionew = usuarionew;
       this.passnew = passnew;
       this.usuario = usuario;
       this.modificado = modificado;
       this.idCliente = idCliente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNomant() {
        return this.nomant;
    }
    
    public void setNomant(String nomant) {
        this.nomant = nomant;
    }
    public String getApatant() {
        return this.apatant;
    }
    
    public void setApatant(String apatant) {
        this.apatant = apatant;
    }
    public String getAmatant() {
        return this.amatant;
    }
    
    public void setAmatant(String amatant) {
        this.amatant = amatant;
    }
    public String getDireccionant() {
        return this.direccionant;
    }
    
    public void setDireccionant(String direccionant) {
        this.direccionant = direccionant;
    }
    public Date getFenacant() {
        return this.fenacant;
    }
    
    public void setFenacant(Date fenacant) {
        this.fenacant = fenacant;
    }
    public Long getTelefonoant() {
        return this.telefonoant;
    }
    
    public void setTelefonoant(Long telefonoant) {
        this.telefonoant = telefonoant;
    }
    public String getEmailant() {
        return this.emailant;
    }
    
    public void setEmailant(String emailant) {
        this.emailant = emailant;
    }
    public String getUsuarioant() {
        return this.usuarioant;
    }
    
    public void setUsuarioant(String usuarioant) {
        this.usuarioant = usuarioant;
    }
    public String getPassant() {
        return this.passant;
    }
    
    public void setPassant(String passant) {
        this.passant = passant;
    }
    public String getNomnew() {
        return this.nomnew;
    }
    
    public void setNomnew(String nomnew) {
        this.nomnew = nomnew;
    }
    public String getApatnew() {
        return this.apatnew;
    }
    
    public void setApatnew(String apatnew) {
        this.apatnew = apatnew;
    }
    public String getAmatnew() {
        return this.amatnew;
    }
    
    public void setAmatnew(String amatnew) {
        this.amatnew = amatnew;
    }
    public String getDireccionnew() {
        return this.direccionnew;
    }
    
    public void setDireccionnew(String direccionnew) {
        this.direccionnew = direccionnew;
    }
    public Date getFenacnew() {
        return this.fenacnew;
    }
    
    public void setFenacnew(Date fenacnew) {
        this.fenacnew = fenacnew;
    }
    public Long getTelefononew() {
        return this.telefononew;
    }
    
    public void setTelefononew(Long telefononew) {
        this.telefononew = telefononew;
    }
    public String getEmailnew() {
        return this.emailnew;
    }
    
    public void setEmailnew(String emailnew) {
        this.emailnew = emailnew;
    }
    public String getUsuarionew() {
        return this.usuarionew;
    }
    
    public void setUsuarionew(String usuarionew) {
        this.usuarionew = usuarionew;
    }
    public String getPassnew() {
        return this.passnew;
    }
    
    public void setPassnew(String passnew) {
        this.passnew = passnew;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Date modificado) {
        this.modificado = modificado;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }




}


