package model;
// Generated 24/05/2019 03:33:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaFactura generated by hbm2java
 */
public class AuditoriaFactura  implements java.io.Serializable {


     private int id;
     private Integer idClienteant;
     private Double totalant;
     private Date fechaant;
     private Integer idClientenew;
     private Double totalnew;
     private Date fechanew;
     private String usuario;
     private Date modificado;
     private Integer numFactura;

    public AuditoriaFactura() {
    }

	
    public AuditoriaFactura(int id) {
        this.id = id;
    }
    public AuditoriaFactura(int id, Integer idClienteant, Double totalant, Date fechaant, Integer idClientenew, Double totalnew, Date fechanew, String usuario, Date modificado, Integer numFactura) {
       this.id = id;
       this.idClienteant = idClienteant;
       this.totalant = totalant;
       this.fechaant = fechaant;
       this.idClientenew = idClientenew;
       this.totalnew = totalnew;
       this.fechanew = fechanew;
       this.usuario = usuario;
       this.modificado = modificado;
       this.numFactura = numFactura;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdClienteant() {
        return this.idClienteant;
    }
    
    public void setIdClienteant(Integer idClienteant) {
        this.idClienteant = idClienteant;
    }
    public Double getTotalant() {
        return this.totalant;
    }
    
    public void setTotalant(Double totalant) {
        this.totalant = totalant;
    }
    public Date getFechaant() {
        return this.fechaant;
    }
    
    public void setFechaant(Date fechaant) {
        this.fechaant = fechaant;
    }
    public Integer getIdClientenew() {
        return this.idClientenew;
    }
    
    public void setIdClientenew(Integer idClientenew) {
        this.idClientenew = idClientenew;
    }
    public Double getTotalnew() {
        return this.totalnew;
    }
    
    public void setTotalnew(Double totalnew) {
        this.totalnew = totalnew;
    }
    public Date getFechanew() {
        return this.fechanew;
    }
    
    public void setFechanew(Date fechanew) {
        this.fechanew = fechanew;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Date modificado) {
        this.modificado = modificado;
    }
    public Integer getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(Integer numFactura) {
        this.numFactura = numFactura;
    }




}


