package model;
// Generated 27/05/2019 10:40:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaCategoria generated by hbm2java
 */
public class AuditoriaCategoria  implements java.io.Serializable {


     private int id;
     private String nombreant;
     private String descripcionant;
     private String nombrenew;
     private String descripcionnew;
     private String usuario;
     private Date modificado;
     private Integer idCategoria;

    public AuditoriaCategoria() {
    }

	
    public AuditoriaCategoria(int id) {
        this.id = id;
    }
    public AuditoriaCategoria(int id, String nombreant, String descripcionant, String nombrenew, String descripcionnew, String usuario, Date modificado, Integer idCategoria) {
       this.id = id;
       this.nombreant = nombreant;
       this.descripcionant = descripcionant;
       this.nombrenew = nombrenew;
       this.descripcionnew = descripcionnew;
       this.usuario = usuario;
       this.modificado = modificado;
       this.idCategoria = idCategoria;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreant() {
        return this.nombreant;
    }
    
    public void setNombreant(String nombreant) {
        this.nombreant = nombreant;
    }
    public String getDescripcionant() {
        return this.descripcionant;
    }
    
    public void setDescripcionant(String descripcionant) {
        this.descripcionant = descripcionant;
    }
    public String getNombrenew() {
        return this.nombrenew;
    }
    
    public void setNombrenew(String nombrenew) {
        this.nombrenew = nombrenew;
    }
    public String getDescripcionnew() {
        return this.descripcionnew;
    }
    
    public void setDescripcionnew(String descripcionnew) {
        this.descripcionnew = descripcionnew;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Date modificado) {
        this.modificado = modificado;
    }
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }




}


