package model;
// Generated 27/05/2019 10:40:28 PM by Hibernate Tools 4.3.1



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private int numDetalle;
     private Factura factura;
     private String nombreProd;
     private Integer cantidad;
     private Double precio;

    public Detalle() {
    }

    public Detalle(Factura factura, String nombreProd, Integer cantidad, Double precio) {
       this.factura = factura;
       this.nombreProd = nombreProd;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public int getNumDetalle() {
        return this.numDetalle;
    }
    
    public void setNumDetalle(int numDetalle) {
        this.numDetalle = numDetalle;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getNombreProd() {
        return this.nombreProd;
    }
    
    public void setNombreProd(String nombreProd) {
        this.nombreProd = nombreProd;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


