package model;
// Generated 24/05/2019 03:33:36 PM by Hibernate Tools 4.3.1



/**
 * Envio generated by hbm2java
 */
public class Envio  implements java.io.Serializable {


     private int idEnvio;
     private Factura factura;
     private String direccion;
     private Integer cp;
     private String estado;

    public Envio() {
    }

	
    public Envio(int idEnvio) {
        this.idEnvio = idEnvio;
    }
    public Envio(int idEnvio, Factura factura, String direccion, Integer cp, String estado) {
       this.idEnvio = idEnvio;
       this.factura = factura;
       this.direccion = direccion;
       this.cp = cp;
       this.estado = estado;
    }
   
    public int getIdEnvio() {
        return this.idEnvio;
    }
    
    public void setIdEnvio(int idEnvio) {
        this.idEnvio = idEnvio;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


